x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ~/.nanobot:/root/.nanobot

services:

  nanobot-hr:
    container_name: nanobot-hr
    <<: *common-config
    volumes:
      - ~/.nanobot-hr:/root/.nanobot
      - ~/.config/google-docs-mcp:/root/.config/google-docs-mcp
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18791:18790
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  nanobot-alibaba-eos:
    container_name: nanobot-alibaba-eos
    <<: *common-config
    volumes:
      - ~/.nanobot-alibaba-eos:/root/.nanobot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18793:18790
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  nanobot-swj:
    container_name: nanobot-swj
    <<: *common-config
    volumes:
      - ~/.nanobot-swj:/root/.nanobot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["gateway"]
    restart: unless-stopped
    ports:
      - 18794:18790
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true